INSERT INTO CATEGORIES (libelle) Values ('Animalerie')
INSERT INTO CATEGORIES (libelle) Values ('Bateaux, voile et nautisme')
INSERT INTO CATEGORIES (libelle) Values ('PME, artisans et agriculteurs')
INSERT INTO CATEGORIES (libelle) Values ('Appareils photo et caméscopes')
INSERT INTO CATEGORIES (libelle) Values ('Bijoux et montres')
INSERT INTO CATEGORIES (libelle) Values ('Jouets et jeux')
INSERT INTO CATEGORIES (libelle) Values ('Produits de beauté, bien être')
INSERT INTO CATEGORIES (libelle) Values ('Art et antiquités')
INSERT INTO CATEGORIES (libelle) Values ('Collections')
INSERT INTO CATEGORIES (libelle) Values ('Articles électroménager')
INSERT INTO CATEGORIES (libelle) Values ('Livres, bds et revues')
INSERT INTO CATEGORIES (libelle) Values ('Sports et vacances')
INSERT INTO CATEGORIES (libelle) Values ('Articles de loisir créatif')
INSERT INTO CATEGORIES (libelle) Values ('Matériel audio et vidéo')
INSERT INTO CATEGORIES (libelle) Values ('Articles pour bébé')
INSERT INTO CATEGORIES (libelle) Values ('Céramiques et verres')
INSERT INTO CATEGORIES (libelle) Values ('Matériel de bricolage')
INSERT INTO CATEGORIES (libelle) Values ('Timbres')
INSERT INTO CATEGORIES (libelle) Values ('Articles jardin et terrasse')
INSERT INTO CATEGORIES (libelle) Values ('Immobilier')
INSERT INTO CATEGORIES (libelle) Values ('Monnaies')
INSERT INTO CATEGORIES (libelle) Values ('Téléphonie et mobilité')
INSERT INTO CATEGORIES (libelle) Values ('Informatique et réseaux')
INSERT INTO CATEGORIES (libelle) Values ('Articles pour la maison')
INSERT INTO CATEGORIES (libelle) Values ('Musique, CD et vinyles')
INSERT INTO CATEGORIES (libelle) Values ('Vêtements et accessoires')
INSERT INTO CATEGORIES (libelle) Values ('Instruments de musique')
INSERT INTO CATEGORIES (libelle) Values ('Automobiles et motocyclettes')

